// "": "",
export default {
	"en": {
		"projectName": "Topsi Project Manager",
		"firstUseWelcome": "Welcome to Topsi Project Manager",
		"firstUseContent": `<strong>Press CTRL+D at any time to display the help page.</strong> <br /> Since this is the first time you're using this application, please setup the next default values to be used by the application. <br/> <br/> All the settings can be
		<strong>modified </strong> at any time.`,
		"firstUseSetupFolder": "Setup the default folder to store your projects.",
		"firstUseSetupColor": "Setup the default application color",
		"aboutContent": "Topsi Project Manager is a simple kanban board software built with electron and vuejs. It supports all three major platforms (Windows, Linux and OSX). It's free and Open Source under the AGPL V3 Clause.<br /><br /><br /> <strong>github: </strong> <a>https://github.com/Physiix/topsi-project-manager</a>",
		"searchLabel": "Search by title, tags, project...",
		"helperTitle": "Helper/Shortcuts",
		"newMilestoneLabel": "Milestone Name",
		"category": "Category",
		"milestone": "Milestone",
		"noTagFound": "No tag found. Tags needs to be created before being used.",
		"projectDialogFolderLabel": "Project's save directory",
		"export": "Export",
		"general": "General",
		"about": "About",
		"edit": "Edit",
		"save": "Save",
		"cancel": "Cancel",
		"browse": "Browse",
		"done": "Done",
		"close": "Close",
	},
	"pt": {
       	"projectName": "Gerenciador de Projeto Topsi",
       	"firstUseWelcome": "Bem Vindo ao Gerenciador de Projeto Topsi",
       	"firstUseContent": `<strong>Pressione CTRL + D para exibir a página de ajuda.</strong> <br /> Como esta é a primeira vez que você está usando este aplicativo, por favor, configure os próximos valores padrão a serem usados pelo aplicativo. <br/> <br/> Todas as configurações podem ser
       	<strong> modificadas </strong> a qualquer momento.`,
       	"firstUseSetupFolder": "Configure a pasta padrão para armazenar seus projetos.",
       	"firstUseSetupColor": "Configurar a cor do aplicativo padrão",
       	"aboutContent": "O Gerenciador de Projeto Topsi é um software de quadro kanban simples, construído com electron e vuejs. Suporta todas as três principais plataformas (Windows, Linux e OSX). É grátis e Open Source sob a cláusula AGPL V3.<br /><br /><br /> <strong>github: </strong> <a>https://github.com/Physiix/topsi-project-manager</a>",
       	"searchLabel": "Pesquise por título, tags, projeto ...",
       	"helperTitle": "Ajuda/Atalhos",
       	"newMilestoneLabel": "Nome da Milestone ",
       	"category": "Categoria",
       	"milestone": "Milestone",
       	"noTagFound": "Nenhuma tag encontrada. As tags precisam ser criadas antes de serem usadas.",
       	"projectDialogFolderLabel": "Diretório de salvamento do projeto",
       	"export": "Exportar",
       	"general": "Geral",
       	"about": "Sobre",
       	"edit": "Editar",
       	"save": "Salvar",
       	"cancel": "Cancelar",
       	"browse": "Browse",
       	"done": "Feito",
       	"close": "Fechar",
    },
}

//