// "": "",
export default {
	"en": {
		"projectName": "Topsi Project Manager",
		"firstUseWelcome": "Welcome to Topsi Project Manager",
		"firstUseContent": `<strong>Press CTRL+D at any time to display the help page.</strong> <br /> Since this is the first time you're using this application, please setup the next default values to be used by the application. <br/> <br/> All the settings can be
		<strong>modified </strong> at any time.`,
		"firstUseSetupFolder": "Setup the default folder to store your projects.",
		"firstUseSetupColor": "Setup the default application color",
		"aboutContent": "Topsi Project Manager is a simple kanban board software built with electron and vuejs. It supports all three major platforms (Windows, Linux and OSX). It's free and Open Source under the AGPL V3 Clause.<br /><br /><br /> <strong>github: </strong> <a>https://github.com/Physiix/topsi-project-manager</a>",
		"searchLabel": "Search by title, tags, project...",
		"helperTitle": "Helper/Shortcuts",
		"newMilestoneLabel": "Milestone Name",
		"category": "Category",
		"milestone": "Milestone",
		"noTagFound": "No tag found. Tags needs to be created before being used.",
		"projectDialogFolderLabel": "Project's save directory",
		"newProject": "New project",
		"exportProject": "Export Project",
		"importProject": "Import Project",
		"settings": "Settings",
		"layoutAndOptions": "Layout & Options",
		"project": "Project",
		"title": "Title",
		"tags": "Tags",
		"backToProjects": "Back to projects",
		"searchInNotes": "Search in notes (CTRL + F)",
		"addNewNote": "Add a new Note",
		"editProject": "Edit Project",
		"milestones": "Milestones",
		"noTagsCreated": "No tags created yet. ",
		"confirmDeleteMessage": "Are you sure you want to delete this project ?",
		"export": "Export",
		"general": "General",
		"about": "About",
		"edit": "Edit",
		"save": "Save",
		"cancel": "Cancel",
		"browse": "Browse",
		"done": "Done",
		"close": "Close",
		"delete": "Delete",
	},
}

//